replicaCount: 1

containerName: ""

image:
  registry: quay.io
  username: zagaos
  name: apm-ingestion-pyiceberg
  pullPolicy: IfNotPresent
  tag: ecfa9ce
  strategy: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

securityContext: {}

ports: {}

service:
  - enabled: false
    serviceType: ClusterIP
  - enabled: false
    serviceType: LoadBalancer


secretsEnv: {}

configmapEnv:
  - name: ""
    mount: ""
    mountPath: ""
    filePath: false
    data:
      BUCKET_NAME: 's3a://observability-metrics/metrics'
      CONSUMER_GROUP_ID: apm_metric
      KAFKA_TOPIC: apmmetrics
      NAME_SPACE: apm_metrics
      SCRIPT_TO_RUN: metrics
      TABLE_NAME: metric
      KAFKA_BOOTSTRAP_SERVER: 'telemetry-kafka-bootstrap.observability-kafka.svc.cluster.local:9092'
      URI: 'thrift://hive-metastore.observability-datamesh.svc.cluster.local:9083'
      S3_ENDPOINT: 'http://minio.observability-datamesh.svc.cluster.local:9000'
      ACCESS_KEY: minioAdmin
      SECRET_KEY: minio1234

probes:
  readiness:

  liveness:


volumes: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
