{{- range .Values.service }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmetadata.fullname" $ }}-{{ .serviceType | lower }}
  labels:
    {{- include "openmetadata.labels" $ | nindent 4 }}
spec:
  type: {{ .serviceType }}
  ports:
    {{- range $.Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "openmetadata.selectorLabels" $ | nindent 4 }}

---

{{- end }}
{{- end }}