{{- range .Values.secretsEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" $ }}-{{ .name }}
  labels:
    {{- include "postgresql.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}