replicaCount: 1

image:
  registry: quay.io
  username: osclimate
  name: postgresql-13
  pullPolicy: IfNotPresent
  tag: 1-101

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432


service:
  - enabled: true
    serviceType: ClusterIP
  - enabled: false
    serviceType: LoadBalancer

configmapEnv: {}

secretsEnv: 
  - name: postgres-secret
    data:
      POSTGRESQL_ADMIN_PASSWORD: admin123$
      POSTGRESQL_DATABASE: hivemetadb
      POSTGRESQL_PASSWORD: hivemeta123$
      POSTGRESQL_USER: hive

volumes: 
  - kind: PersistentVolumeClaim
    apiVersion: v1
    accessModes: ReadWriteOnce
    volumeName: ""
    mountPath: /storage
    storageSize: "2Gi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources: 
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 300Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""

nodeSelector: {}

tolerations: []

affinity: {}