{{- range .Values.configmapEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-postgresql.fullname" $ }}-{{ .name }}
  labels:
    {{- include "admin-postgresql.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}