{{- if and .Values.routes.enabled .Values.ingress.enabled }}
{{- fail "Both 'routes.enabled' and 'ingress.enabled' cannot be true at the same time. Please set only one of them to true." }}
{{- end }}

{{- $clusterIPServiceFound := false }}
{{- range .Values.service }}
  {{- if eq .serviceType "ClusterIP" }}
    {{- $clusterIPServiceFound = true }}
  {{- end }}
{{- end }}

{{- if and $clusterIPServiceFound .Values.routes.enabled }}
  {{- range .Values.ports }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "query.fullname" $ }}-{{ .name }}
  labels:
    {{- include "query.labels" $ | nindent 4 }}
spec:
  subdomain: {{ .subdomainName }}
  to:
    kind: Service
    name: {{ include "query.fullname" $ }}-clusterip
  port:
    targetPort: {{ .name }}
  {{- if $.Values.routes.tls.enabled }}
  tls:
    termination: {{ $.Values.routes.tls.termination }}
    insecureEdgeTerminationPolicy: {{ $.Values.routes.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
---
  {{- end }}
{{- end }}

