apiVersion: v2
name: apm
description: A Helm chart for Kubernetes

version: 1.0.0

dependencies:
  - name: ingestion-traces
    version: "1.0.0"
    repository: "file://charts/01-ingestion-traces"
    condition: subcharts.ingestion-traces
    tags:
      - ingestion-traces
  - name: ingestion-logs
    version: "1.0.0"
    repository: "file://charts/01-ingestion-logs"
    condition: subcharts.ingestion-logs
    tags:
      - ingestion-logs
  - name: ingestion-metrics
    version: "1.0.0"
    repository: "file://charts/01-ingestion-metrics"
    condition: subcharts.ingestion-metrics
    tags:
      - ingestion-metrics
  - name: query
    version: "1.0.0"
    repository: "file://charts/02-query"
    condition: subcharts.query
    tags:
      - query
  - name: dashboard
    version: "1.0.0"
    repository: "file://charts/03-dashboard"
    condition: subcharts.dashboard
    tags:
      - dashboard