{{- range .Values.containers }}
  {{- $container := . }}
  {{- range $container.secretsEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .name }}{{ .name }}{{ else }}{{ include "airflow.fullname" $ }}-secret{{ end }}
  labels:
    {{- include "airflow.labels" $ | nindent 4 }}
type: Opaque
data:
{{- if kindIs "slice" .data }}
  {{- range .data }}
    {{- if and (hasKey . "name") (hasKey . "path") }}
    {{ .name }}: |
{{ $.Files.Get .path | b64enc | nindent 6 | trimSuffix "\n" }}
    {{- end }}
  {{- end }}
{{- else if kindIs "map" .data }}
  {{- range $key, $value := .data }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
---
  {{- end }}
{{- end }}

---

{{- range .Values.initContainers }}
  {{- $initContainer := . }}
  {{- range $initContainer.secretsEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .name }}{{ .name }}{{ else }}{{ include "airflow.fullname" $ }}-secret{{ end }}
  labels:
    {{- include "airflow.labels" $ | nindent 4 }}
type: Opaque
data:
{{- if kindIs "slice" .data }}
  {{- range .data }}
    {{- if and (hasKey . "name") (hasKey . "path") }}
    {{ .name }}: |
{{ $.Files.Get .path | b64enc | nindent 6 | trimSuffix "\n" }}
    {{- end }}
  {{- end }}
{{- else if kindIs "map" .data }}
  {{- range $key, $value := .data }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
---
  {{- end }}
{{- end }}

---

{{- range .Values.secretsEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .name }}{{ .name }}{{ else }}{{ include "airflow.fullname" $ }}-secret{{ end }}
  labels:
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/part-of: {{ include "airflow.fullname" $ }}
    app.kubernetes.io/managed-by: Helm
data:
{{- if kindIs "slice" .data }}
{{- range .data }}
  {{- if and (hasKey . "name") (hasKey . "path") }}
  {{ .name }}: |-
{{- $.Files.Get .path | nindent 4 | trimSuffix "\n" }}
  {{- end }}
{{- end }}
{{- else if kindIs "map" .data }}
{{- range $key, $value := .data }}
  {{ $key }}: "{{ $value | b64enc }}"
{{- end }}
{{- end }}
---
{{- end }}