replicaCount: 1

image:
  registry: quay.io
  username: osclimate
  name: hive-metastore
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ports:
  - name: 9083-tcp
    port: 9083
    protocol: TCP
    targetPort: 9083

service:
  - enabled: true
    serviceType: ClusterIP
  - enabled: false
    serviceType: LoadBalancer


secretsEnv:
  - name: ""
    # mount: ""
    # mountPath: ""
    data:
      AWS_ACCESS_KEY_ID: minioAdmin
      AWS_SECRET_ACCESS_KEY: minio1234
      DATABASE_DB: hivemetadb
      DATABASE_USER: hive
      DATABASE_PASSWORD: hivemeta123$

configmapEnv:
  - name: ""
    # mount: ""
    # mountPath: ""
    data:
      S3_ENDPOINT_URL: 'http://minio.$(NAMESPACE).svc.cluster.local:9000'
      S3_PREFIX: data
      S3_BUCKET: pcaf
      DATABASE_HOST: trino-hive-postgresql-clusterip
      DATABASE_PORT: "5432"

volumes: 
  - type: EmptyDir
    volumeName: hadoop-config
    mountPath: /opt/hadoop/etc/hadoop
  - type: EmptyDir
    volumeName: hive-config
    mountPath: /opt/hive-metastore/conf

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
