replicaCount: 1

containerName: ""

image:
  registry: quay.io
  username: zagaos
  name: infra-pyiceberg-query
  pullPolicy: IfNotPresent
  tag: v4
  strategy: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""


ports:
  - name: https
    subdomainName: infra-query
    port: 8000
    protocol: TCP
    targetPort: 8000
    routePolicy:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

service:
  - enabled: true
    serviceType: ClusterIP
  - enabled: false
    serviceType: LoadBalancer

routes:
  enabled: true
  tls: false
  annotations: {}

ingress:
  enabled: false
  className: ""
  tls: false
  annotations: {}

secretsEnv: {}

configmapEnv:
  - name: ""
    mount: ""
    mountPath: ""
    data:
      HIVE_THRIFT_URI: thrift://hive-metastore.observability-datamesh.svc.cluster.local:9083
      MINIO_ACCSESS_KEY_ID: minioAdmin
      MINIO_SECRET_ACCSESS_KEY: minio1234
      PY_IO_IMPL: pyiceberg.io.pyarrow.PyArrowFileIO
      MINIO_ENDPOINT: http://minio.observability-datamesh.svc.cluster.local:9000
      NODE_TABLE_NAME: node
      NODE_NAME_SPACE: infra_node
      POD_TABLE_NAME: pod
      POD_NAME_SPACE: infra_pod
      EVENT_NAME_SPACE: infra_event
      EVENT_TABLE_NAME: event

probes:
  readiness:
  liveness:

volumes: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}