nameOverride: ""

rbac:
  enabled: true

  serviceAccount:
    create: true
    annotations: {}

  role:
    create: true
    annotations: {}

  roleBinding:
    create: true
    annotations: {}
  
  scc:
    create: true
    annotations:
      kubernetes.io/description: 'privileged allows access to trino'

subcharts:
  hive-postgresql: true
  hive-metastore: true
  coordinator: true
  worker: true

###########################################################3

hive-postgresql: 
  replicaCount: 1

  image:
    registry: quay.io
    username: osclimate
    name: postgresql-13
    pullPolicy: IfNotPresent
    tag: 1-101

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432


  service:
    - enabled: true
      serviceType: ClusterIP
    - enabled: false
      serviceType: LoadBalancer

  configmapEnv:
    - name: configmap
      data:
        POSTGRESQL_ADMIN_PASSWORD: admin123$
        POSTGRESQL_DATABASE: hivemetadb
        POSTGRESQL_PASSWORD: hivemeta123$
        POSTGRESQL_USER: hive

  volumes: 
    - kind: PersistentVolumeClaim
      apiVersion: v1
      accessModes: ReadWriteOnce
      volumeName: ""
      mountPath: /storage
      storageSize: "4Gi"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  resources: {}

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  nodeSelector: {}

  tolerations: []

  affinity: {}

########################################################

hive-metastore: 

  replicaCount: 1

  image:
    registry: quay.io
    username: osclimate
    name: hive-metastore
    pullPolicy: IfNotPresent
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  ports:
    - name: 9083-tcp
      port: 9083
      protocol: TCP
      targetPort: 9083

  service:
    - enabled: true
      serviceType: ClusterIP
    - enabled: false
      serviceType: LoadBalancer


  secretsEnv:
    - name: ""
      # mount: ""
      # mountPath: ""
      data:
        AWS_ACCESS_KEY_ID: minioAdmin
        AWS_SECRET_ACCESS_KEY: minio1234
        DATABASE_DB: hivemetadb
        DATABASE_USER: hive
        DATABASE_PASSWORD: hivemeta123$

  configmapEnv:
    - name: ""
      # mount: ""
      # mountPath: ""
      data:
        S3_ENDPOINT_URL: 'http://minio.$(NAMESPACE).svc.cluster.local:9000'
        S3_PREFIX: data
        S3_BUCKET: pcaf
        DATABASE_HOST: trino-hive-postgresql-clusterip
        DATABASE_PORT: "5432"

  volumes: 
    - type: EmptyDir
      volumeName: hadoop-config
      mountPath: /opt/hadoop/etc/hadoop
    - type: EmptyDir
      volumeName: hive-config
      mountPath: /opt/hive-metastore/conf

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

#######################################################

coordinator: 

  replicaCount: 1

  image:
    registry: quay.io
    username: osclimate
    name: trino
    pullPolicy: IfNotPresent
    tag: latest
    strategy: Recreate

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      subdomainName: trino-coordinator
      tls:
        enabled: true
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
      subdomainName: trino-coordinator-https
      tls:
        enabled: true
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  service:
    - enabled: true
      serviceType: ClusterIP
    - enabled: false
      serviceType: LoadBalancer

  routes:
    enabled: true

  ingress:
    enabled: false
    domain: apps.zagaopenshift.zagaopensource.com
    annotations:
      cert-manager.io/cluster-issuer: zagaadmin-cluster-issuer

  secretsEnv:
    - name: trino-coordinator-secret
      mount: ""
      mountPath: ""
      data:
        AWS_ACCESS_KEY_ID: minioAdmin
        AWS_SECRET_KEY_ID: admin1234
        INTER_COMM_SHARED_SECRET: kzs71nsYBRr8cysT62zb6P+VT8YsVi/eASfNKUJkvPDce6aof6FLyM/0EDA8qK46P8sD2jXBTTe7cKX0MEqTS2UNZ7YdYWHUUoSG2nLgEryZbqlEkguYWs2dSSYkzv9DIPMtRvGxmNdQ6HGGscrqsFkeK7kSCd6mn5YNskIv6Z665gquqq+SlqV5UylFDcXhB6Z7oWuZ2fq3WONVWtTIhYP73YO8iDORG2afkqPQhRKTw848YQVrcqKAIOX6sirMb5KE1BP0yXz533J71vFuMqkvTBrFV3lkvAq+/7W4iA9Xn9WDJ8TGgcwB7jFOLH9htKYrXtO2XgMsWxizi7XbFzXsPEreqndhZEX7i6U0/K22kCWRy7/lcH+JMQAzq3J+qxl1KqTLVTfu3iSIKUj093/wR0EPcH282a+HMzk/5E1aGk3uV40M/1wQwlEDzBRaGtLtW7tyFHX+sc29nLgkOFAPknwqnYoSR7FDEgO+CrB00zNeY1lS1Xx8OCEfGgg+y5zK7pSMm7cuq8PHjENXCsWOY3xNkJLKsf9mWiWLZhxE1G6EQMG8WPz2r+DhBskTaoHaRPCfcD3/2vaDEjvfK/9kek94g00JcjJB9HQQe3tINmEBxkA8SjIWZe40kcPU0hbKqeA8WFzUgwsB/2KxFvTcPpRvNKseozZZxL/2Dlk=
    - name: trino-coordinator-keystore
      mount: true
      mountPath: /etc/trino/keystore
      filePath: true
      data:
        - name: keystore.jks
          path: configs/keystores/keystore.jks
    - name: trino-coordinator-keystore-p12
      mount: true
      mountPath: /etc/trino/trino-p12
      filePath: true
      data:
        - name: trino.p12
          path: configs/keystores/trino.p12

  configmapEnv:
    - name: trino-coordinator-configmap
      mount: ""
      mountPath: ""
      data:
        HIVE_DB_EXTERNAL: "true"
        S3_ENDPOINT_URL: http://minio-dev.$(NAMESPACE).svc.cluster.local:9000
        S3_PREFIX: data
        S3_BUCKET: pcaf
        DATABASE_HOST: trino-hive-postgresql
        DATABASE_PORT: "5432"
    - name: trino-coordinator-schemas
      mount: true
      mountPath: /etc/trino/schemas
      filePath: true
      data: 

    - name: trino-coordinator-configs
      mount: true
      mountPath: /etc/trino
      filePath: true
      data:
        - name: config.properties
          path: configs/trino-coordinator/config.properties
        - name: exchange-manager.properties
          path: configs/trino-coordinator/exchange-manager.properties
        - name: group-mapping.properties
          path: configs/trino-coordinator/group-mapping.properties
        - name: group-provider.properties
          path: configs/trino-coordinator/group-provider.properties
        - name: jvm.config
          path: configs/trino-coordinator/jvm.config
        - name: log.properties
          path: configs/trino-coordinator/log.properties      
        - name: node.properties
          path: configs/trino-coordinator/node.properties
        - name: password-authenticator.properties
          path: configs/trino-coordinator/password-authenticator.properties
        - name: password.db
          path: configs/trino-coordinator/password.db

    - name: trino-coordinator-catalog
      mount: true
      mountPath: /etc/trino/catalog
      filePath: true
      data:
        - name: hive.properties
          path: configs/trino-catalog/hive.properties
        - name: iceberg.properties
          path: configs/trino-catalog/iceberg.properties
        - name: tpcds.properties
          path: configs/trino-catalog/tpcds.properties
        - name: tpch.properties
          path: configs/trino-catalog/tpch.properties

  probes:
    readiness:
    liveness:

  volumes: {}

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

#######################################################

worker: 

  replicaCount: 3

  image:
    registry: quay.io
    username: osclimate
    name: trino
    pullPolicy: IfNotPresent
    tag: latest
    strategy: Recreate

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080

  service:
    - enabled: true
      serviceType: ClusterIP
    - enabled: false
      serviceType: LoadBalancer


  secretsEnv:
    - name: trino-worker-config
      mount: ""
      mountPath: ""
      data:
        AWS_ACCESS_KEY_ID: minioAdmin
        AWS_SECRET_KEY_ID: admin1234
        INTER_COMM_SHARED_SECRET: kzs71nsYBRr8cysT62zb6P+VT8YsVi/eASfNKUJkvPDce6aof6FLyM/0EDA8qK46P8sD2jXBTTe7cKX0MEqTS2UNZ7YdYWHUUoSG2nLgEryZbqlEkguYWs2dSSYkzv9DIPMtRvGxmNdQ6HGGscrqsFkeK7kSCd6mn5YNskIv6Z665gquqq+SlqV5UylFDcXhB6Z7oWuZ2fq3WONVWtTIhYP73YO8iDORG2afkqPQhRKTw848YQVrcqKAIOX6sirMb5KE1BP0yXz533J71vFuMqkvTBrFV3lkvAq+/7W4iA9Xn9WDJ8TGgcwB7jFOLH9htKYrXtO2XgMsWxizi7XbFzXsPEreqndhZEX7i6U0/K22kCWRy7/lcH+JMQAzq3J+qxl1KqTLVTfu3iSIKUj093/wR0EPcH282a+HMzk/5E1aGk3uV40M/1wQwlEDzBRaGtLtW7tyFHX+sc29nLgkOFAPknwqnYoSR7FDEgO+CrB00zNeY1lS1Xx8OCEfGgg+y5zK7pSMm7cuq8PHjENXCsWOY3xNkJLKsf9mWiWLZhxE1G6EQMG8WPz2r+DhBskTaoHaRPCfcD3/2vaDEjvfK/9kek94g00JcjJB9HQQe3tINmEBxkA8SjIWZe40kcPU0hbKqeA8WFzUgwsB/2KxFvTcPpRvNKseozZZxL/2Dlk=

  configmapEnv:
    - name: trino-worker-configmap
      mount: ""
      mountPath: ""
      data:
        TRINO_COORDINATOR_HOSTNAME: http://trino-coordinator-dev.$(NAMESPACE).svc.cluster.local:8080

    - name: trino-worker-schemas
      mount: true
      mountPath: /etc/trino/schemas
      filePath: true
      data: 

    - name: trino-worker-configs
      mount: true
      mountPath: /etc/trino
      filePath: true
      data:
        - name: config.properties
          path: configs/trino-worker/config.properties
        - name: exchange-manager.properties
          path: configs/trino-worker/exchange-manager.properties
        - name: jvm.config
          path: configs/trino-worker/jvm.config
        - name: log.properties
          path: configs/trino-worker/log.properties
        - name: node.properties
          path: configs/trino-worker/node.properties

    - name: trino-worker-catalog
      mount: true
      mountPath: /etc/trino/catalog
      filePath: true
      data:
        - name: hive.properties
          path: configs/trino-catalog/hive.properties
        - name: iceberg.properties
          path: configs/trino-catalog/iceberg.properties
        - name: tpcds.properties
          path: configs/trino-catalog/tpcds.properties
        - name: tpch.properties
          path: configs/trino-catalog/tpch.properties

  probes:
    readiness:
        httpGet:
          path: /v1/info
          port: http
          scheme: HTTP
        initialDelaySeconds: 20
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 6
    liveness:
        httpGet:
          path: /v1/info
          port: http
          scheme: HTTP
        initialDelaySeconds: 20
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 6

  volumes: {}

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
